apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodefortunes
spec:
  selector:
    matchLabels:
      app: nodefortunes
  replicas: 2
  template:
    metadata:
      labels:
        app: nodefortunes
    spec:
      containers:
      - name: nodefortunes
        image: dockerhub/nodeimage
        env:
        - name: NODE_ENV
          value: prod
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-fortune
spec:
  type: NodePort
  selector:
    app: nodefortunes
  ports:
  - port: 3000
    targetPort: 3000