apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonfortunes
spec:
  selector:
    matchLabels:
      app: pythonfortunes
  replicas: 2
  template:
    metadata:
      labels:
        app: pythonfortunes
    spec:
      containers:
      - name: pythonfortunes
        image: abree05/k8-python-fortune:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-fortune
spec:
  type: NodePort
  selector:
    app: pythonfortunes
  ports:
  - port: 5000
    nodePort: 30050